#!/bin/sh
set -eu

# Generated by the make-submission skill. Keep this file outside the bundle.
script_dir=$(CDPATH= cd -P "$(dirname "$0")" && pwd)
bundle_name=qwen3-vl-4b-lora-both-official-epoch8-v2-20260727
bundle_dir="${script_dir}/${bundle_name}"

if [ ! -d "${bundle_dir}" ]; then
  printf 'Bundle directory not found: %s\n' "${bundle_dir}" >&2
  exit 1
fi

rsync --archive --hard-links --human-readable --partial --info=progress2 \
  --protect-args -- \
  "${bundle_dir}" \
  gatept8:/raid2/qianye/orena/procedure/
